version: "3.9"
services:
  archive_downloader:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ./output:/ad_output:rw
      - ./urls.txt:/ad_urls.txt:ro
    command:
      - "-e"
      - "$AD_EMAIL"
      - "-p"
      - "$AD_PASSWORD"
      - "-r"
      - "$AD_RESOLUTION"
      - "-d"
      - "/ad_output"
      - "-f"
      - "/ad_urls.txt"
